theme: jekyll-theme-minimal
baseurl: /udwue
title: udwue infos
description: Zahlen des U&D, zum Teil geschätzt. Keine Gewähr. <br> <a href="UundD_Foerderbedarf23_24_20231108_DD.pdf" target="_blank">Diagramm als PDF.</a>

