theme: jekyll-theme-minimal
title: udwue infos
description: Zahlen des U&D, zum Teil geschätzt. Keine Gewähr. <br> <a href="https://github.com/gpsloco/udwue/UundD_Foerderbedarf23_24_20231108_DD.pdf" target="_blank">Diagramm als PDF.</a>

