theme: jekyll-theme-minimal
title: udwue infos
description: Zahlen des U&D, zum Teil geschätzt. Keine Gewähr. <br> <a href="gpsloco.github.io/udwue/UundD_Förderbedarf23_24_20231108_DD.pdf" target="_blank">Präsentation der Zahlen als PDF.</a>

